import basic_get_stock_basic
import basic_get_trade_cal
import basic_get_name_change

basic_get_stock_basic.get_data_from_tushare()
basic_get_trade_cal.get_data_from_tushare()
basic_get_name_change.get_data_from_tushare()
