# Generated by Django 3.1.7 on 2021-03-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushare_data', '0002_auto_20210327_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tusharestockbasic',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
