# Generated by Django 3.1.7 on 2021-03-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushare_data', '0003_auto_20210327_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='TushareTradeCal',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('exchange', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('is_open', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tushare_trade_cal',
            },
        ),
    ]
