# Generated by Django 3.1.7 on 2021-03-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tushare_data', '0004_tusharetradecal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tusharetradecal',
            old_name='end_date',
            new_name='cal_date',
        ),
        migrations.RenameField(
            model_name='tusharetradecal',
            old_name='start_date',
            new_name='pretrade_date',
        ),
    ]
