# Generated by Django 3.1.7 on 2021-03-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushare_data', '0005_auto_20210327_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='TushareNameChange',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ts_code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.CharField(blank=True, max_length=100, null=True)),
                ('end_date', models.CharField(blank=True, max_length=100, null=True)),
                ('ann_date', models.CharField(blank=True, max_length=100, null=True)),
                ('change_reason', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'tushare_name_change',
            },
        ),
    ]
