# Generated by Django 3.1.7 on 2021-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tushare_data', '0006_tusharenamechange'),
    ]

    operations = [
        migrations.CreateModel(
            name='TushareDaily',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('ts_code', models.CharField(blank=True, max_length=100, null=True)),
                ('trade_date', models.CharField(blank=True, max_length=100, null=True)),
                ('open', models.CharField(blank=True, max_length=100, null=True)),
                ('high', models.CharField(blank=True, max_length=100, null=True)),
                ('low', models.CharField(blank=True, max_length=100, null=True)),
                ('close', models.CharField(blank=True, max_length=100, null=True)),
                ('pre_close', models.CharField(blank=True, max_length=100, null=True)),
                ('change', models.CharField(blank=True, max_length=100, null=True)),
                ('pct_chg', models.CharField(blank=True, max_length=100, null=True)),
                ('vol', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tushare_daily',
            },
        ),
    ]
